### Obtener la lista de alternativas
GET http://localhost:5173/api/alternativas

### Crear una nueva alternativa
POST http://localhost:5173/api/alternativas
Content-Type: application/json

{
    "idProyecto": 12,
    "nombre": "JORGE",
    "descripcion": "ESTE ES EL HERMANO DE PEPPA"
}

### Obtener una alternativa específica por su ID y el ID del proyecto
GET http://localhost:5173/api/alternativas/2/3

### Eliminar una alternativa por su ID
DELETE  http://localhost:5173/api/alternativas/eliminar/16/12
