### Obtener la lista de criterios
GET http://localhost:5173/api/criterios

### Obtener un criterio específico por su ID y el ID del proyecto
GET http://localhost:5173/api/criterios/1/3

### Crear un nuevo criterio
POST http://localhost:5173/api/criterios
Content-Type: application/json

{
    "idProyecto": 12,
    "nombre": "NUEVO",
    "descripcion": "EL QUE ESTE MAS GORDO TIENE MAS PUNTAJE",
    "peso": 5
}

### Eliminar una alternativa por su ID
DELETE  http://localhost:5173/api/criterios/eliminar/15/12