### Obtener la lista de proyectos
GET http://localhost:5173/api/proyectos

### Crear un nuevo proyecto
POST http://localhost:5173/api/proyectos
Content-Type: application/json

{
    "Nombre": "DELETE??",
    "Objetivo": "Funciona el delete??"
}

### Obtener un proyecto específico por su ID (ejemplo: ID 1)
GET http://localhost:5173/api/proyectos/3

### Eliminar un proyecto por su ID
DELETE  http://localhost:5173/api/proyectos/eliminar/35

